//ALERT
export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";
export const SUCCESS_CLEAR = "SUCCESS_CLEAR";
export const ERROR_CLEAR = "ERROR_CLEAR";
export const CLEAR = "CLEAR";
// LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
//GET QUESTION
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_ERROR = "GET_QUESTION_ERROR";
//COMMOM
export const START = "START";
export const FAIL = "FAIL";
// USER
export const USER_GET_QUESTION = "USER_GET_QUESTION";
export const USER_POST_RESPONSE = "USER_POST_RESPONSE";
//GET QUESTION
export const GET_ALL_RESPONSES_START = "GET_ALL_RESPONSES_START";
export const GET_ALL_RESPONSES_SUCCESS = "GET_ALL_RESPONSES_SUCCESS";
export const GET_ALL_RESPONSES_ERROR = "GET_ALL_RESPONSES_ERROR";
