//ALERT
export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";
export const SUCCESS_CLEAR = "SUCCESS_CLEAR";
export const ERROR_CLEAR = "ERROR_CLEAR";
export const CLEAR = "CLEAR";
// LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
//GET ALL QUESTION
export const GET_ALL_QUESTION_START = "GET_ALL_QUESTION_START";
export const GET_ALL_QUESTION_SUCCESS = "GET_ALL_QUESTION_SUCCESS";
export const GET_ALL_QUESTION_ERROR = "GET_ALL_QUESTION_ERROR";
// USER GET QUESTION
export const USER_GET_QUESTION_START = "USER_GET_QUESTION_START";
export const USER_GET_QUESTION_SUCCESS = "USER_GET_QUESTION_SUCCESS";
export const USER_GET_QUESTION_ERROR = "USER_GET_QUESTION_ERROR";
// USER POST RESPONSE
export const USER_POST_RESPONSE_START = "USER_POST_RESPONSE_START";
export const USER_POST_RESPONSE_SUCCESS = "USER_POST_RESPONSE_SUCCESS";
export const USER_POST_RESPONSE_ERROR = "USER_POST_RESPONSE_ERROR";
//GET RESPONSES
export const GET_ALL_RESPONSES_START = "GET_ALL_RESPONSES_START";
export const GET_ALL_RESPONSES_SUCCESS = "GET_ALL_RESPONSES_SUCCESS";
export const GET_ALL_RESPONSES_ERROR = "GET_ALL_RESPONSES_ERROR";

//UPDATE STATUS
export const UPDATE_STATUS_START = "UPDATE_STATUS_START";
export const UPDATE_STATUS_SUCCESS= "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_ERROR = "UPDATE_STATUS_ERROR";

//GET QUESTION
export const GET_QUESTION_START = "GET_QUESTION_START";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_ERROR = "GET_QUESTION_ERROR";

// ADD QUESTION
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_ERROR = 'ADD_QUESTION_ERROR';
export const ADD_QUESTION_START = 'ADD_QUESTION_START';

// ADD TEAM MEMBER
export const ADD_TEAM_MEMBER_START = 'ADD_TEAM_MEMBER_START';
export const ADD_TEAM_MEMBER_SUCCESS = 'ADD_TEAM_MEMBER_SUCCESS';
export const ADD_TEAM_MEMBER_ERROR = 'ADD_TEAM_MEMBER_ERROR';

// GET TEAM MEMBER
export const GET_TEAM_MEMBERS_START = 'GET_TEAM_MEMBERS_START';
export const GET_TEAM_MEMBERS_SUCCESS = 'GET_TEAM_MEMBERS_SUCCESS';
export const GET_TEAM_MEMBERS_ERROR = 'GET_TEAM_MEMBERS_ERROR';

//GET PACKAGES
export const GET_PACKAGES_START = 'GET_PACKAGES_START';
export const GET_PACKAGES_SUCCESS = 'GET_PACKAGES_SUCCESS';
export const GET_PACKAGES_ERROR = 'GET_PACKAGES_ERROR';

